### ISSUE TITLE
Add configuration file support

### ISSUE THREAD

**Issue by LarsArtmann** [LarsArtmann/templates#39]
## Description

Currently, all configuration is done via CLI flags. Adding support for a configuration file would make it easier to manage complex validation setups and share configurations across teams.

## Proposed Solution

Add support for a `.repo-validate.yaml` configuration file that can specify:

- Default file groups to check
- Custom template directories
- File exclusions
- Default behavior (dry-run, fix, etc.)
- Custom priority overrides

## Example Configuration

```yaml
# .repo-validate.yaml
defaults:
  dry_run: false
  fix: true
  interactive: false

file_groups:
  - core
  - docker
  - typescript

templates:
  directory: ".repo-templates"

exclusions:
  - "vendor/**"
  - "node_modules/**"

custom_files:
  - path: "custom-file.txt"
    required: true
    priority: "Must-have"
    category: "Custom"
    template: "custom-file.txt.tmpl"
```

## Tasks

- [ ] Design configuration file schema
- [ ] Add YAML parsing support
- [ ] Add configuration file discovery (current dir, home dir, etc.)
- [ ] Add CLI flag to specify custom config file path
- [ ] Ensure CLI flags override config file settings
- [ ] Add validation for configuration file
- [ ] Add documentation and examples

## Acceptance Criteria

- Configuration file is optional (CLI-only usage still works)
- CLI flags take precedence over config file
- Configuration file supports all major settings
- Clear error messages for invalid configuration
- Documentation includes examples

## Related

Enhancement suggestion for PR #21
