### ISSUE TITLE
GitHub Actions Workflow for Automated Label Management

### ISSUE THREAD

**Issue by LarsArtmann** [LarsArtmann/templates#4]
# GitHub Actions for Automated Label Management

## Overview

This issue proposes creating a GitHub Actions workflow to automate the application of standardized labels to repositories using our Terraform module.

### Workflow Location

```
templates/
├── .github/
│   └── workflows/
│       └── github-labels.yml  # The GitHub Actions workflow file
```

### Workflow Features

1. **Manual Trigger with Required Inputs**
   - Repositories input (with defaults for public repositories)
   - Confirmation required ("YES")
   - Dry run option
   - Option to include repositories from secrets

2. **Human in the Loop**
   - Explicit confirmation required
   - Preview of changes before applying
   - Clear reporting of affected repositories

3. **Security Considerations**
   - Private repository names stored in GitHub secrets
   - Appropriate token permissions

### Draft Workflow Definition

```yaml
name: Apply Standardized GitHub Labels

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'Comma-separated list of public repositories to update (leave empty to use defaults)'
        required: false
        default: 'mono,LarsArtmann,Setup-Mac,templates'
        type: string
      
      use_private_repos:
        description: 'Include repositories from secrets'
        required: false
        type: boolean
        default: false
      
      confirm:
        description: 'Type "YES" to confirm you want to apply these changes'
        required: true
        type: string
      
      dry_run:
        description: 'Run in dry-run mode (no changes will be made)'
        required: false
        type: boolean
        default: false

jobs:
  validate-input:
    name: Validate User Input
    runs-on: ubuntu-latest
    steps:
      - name: Check Confirmation
        if: ${{ github.event.inputs.confirm != 'YES' }}
        run: |
          echo "Error: You must type 'YES' (all caps) to confirm the changes."
          exit 1
      
      # Additional validation steps
  
  apply-labels:
    name: Apply Standardized Labels
    needs: validate-input
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4  # Latest stable version
      
      # Configure and run Terraform
```

## Documentation Updates

1. Update main README.md to mention the automation
2. Add section in terraform/github/modules/labels/README.md about the GitHub Actions integration

## Implementation Steps

1. Create the `.github/workflows` directory
2. Implement the workflow file
3. Update documentation
4. Test on a limited set of repositories

## Benefits

1. **Consistency**: Ensures all repositories maintain standardized labels
2. **Automation**: Reduces manual work for repository maintenance
3. **Control**: Human approval and oversight of changes
4. **Transparency**: Clear reporting of what changes are made

## Questions

1. Should we add scheduled runs (e.g., weekly) to ensure labels stay consistent?
2. What default repositories should be included?
3. Are there any specific error handling requirements?

## Related Issues

- #38 (Implement standardized GitHub labels across all repositories with Terraform)
