### ISSUE TITLE
Implement CodeRabbit configuration templates

### ISSUE THREAD

**Issue by LarsArtmann** [LarsArtmann/templates#8]
# Implement CodeRabbit Configuration Templates

## Overview

We should add standardized [CodeRabbit](https://coderabbit.ai/) configuration templates to our repository. CodeRabbit is an AI-powered code review tool that can help improve code quality and development workflow.

## Requirements

1. Create a standard `.coderabbit.yaml` configuration file in the templates repository based on [CodeRabbit documentation](https://docs.coderabbit.ai/getting-started/configure-coderabbit/)
2. Create a README.md with documentation on how to use the remote configuration option
3. Implement verification scripts to validate configuration files

### Standard Configuration

Create a standard `.coderabbit.yaml` configuration file with best practices for:
- Review scope and filters
- Review style and tone
- PR description generation
- Custom instructions
- Language-specific settings

### Remote Configuration Documentation

Create a README.md explaining how to use the remote configuration option:

```yaml
remote_config:
  url: "https://raw.githubusercontent.com/LarsArtmann/templates/master/.coderabbit.yaml"
```

This allows repositories to reference a centralized configuration file that can be updated in one place.

### Verification Scripts

Implement scripts to validate:
1. The main configuration file against the official schema
2. The remote configuration setup

## Benefits

1. **Consistency**: Standardized code review practices across repositories
2. **Maintainability**: Centralized configuration that can be updated in one place
3. **Quality**: Improved code reviews with AI assistance
4. **Efficiency**: Faster onboarding for new repositories

## Related Documentation

- [CodeRabbit Configuration Documentation](https://docs.coderabbit.ai/getting-started/configure-coderabbit/)
- [CodeRabbit Schema](https://coderabbit.ai/integrations/schema.v2.json)
- [Awesome CodeRabbit](https://github.com/coderabbitai/awesome-coderabbit) - Collection of resources and examples

**Comment by LarsArtmann** [comment]
# Example / current config - 2025-04-15

```yaml
language: en-US
tone_instructions: You must use talk like ThePrimeagen (https://www.twitch.tv/ThePrimeagen)!
early_access: true
enable_free_tier: true
auto_resolve_threads: true
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true
  poem: true
  labeling_instructions: []
  path_filters: []
  path_instructions: []
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: true
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
chat:
  auto_reply: true
  create_issues: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
code_generation:
  docstrings:
    language: en-US
```
